Add > Steampipe Cloud > Integrations > Doc > TablePlus
turbot/steampipe-docs pull request #51
Opened 2022-10-21 10:30 UTC by RahulSrivastav14

2022-10-24 18:27 UTC, judell requested changes

2022-10-25 11:39 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +Since the Steampipe Cloud workspace is a PostgreSQL database, you can directly connect TablePlus to your workspace and query the database.
Updated the text as suggested compared to Metabase and Tableau docs. 

But would it be alright to keep the same text in multiple documents?

2022-10-25 11:40 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +# Connect to Steampipe Cloud from TablePlus
Rectified.

2022-10-25 11:43 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +To establish a new connection click on `Create a new connection`, select PostgreSQL and click create. Once the PostgreSQL connection screen pops up, enter the Steampipe Cloud connection details and c
I would agree to use Click Thing instead of Click on Thing. It makes it shorter and straight forward.

2022-10-25 11:57 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +<div style={{"marginTop":"1em", "marginBottom":"1em", "width":"90%"}}>
I've edited and updated the image. The added space is removed and the width is reduced.

2022-10-25 11:58 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +Now select and run the `aws_ec2_ssl_policy` table. TablePlus will display the table's schema and preview the data. You may also choose to export the data in a csv, json or sql format if needed.
Rectified this

2022-10-25 11:59 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +TablePlus comes with the SQL query editor that you may use to write a custom query. For example, we can use the below query in the editor to fetch the S3 buckets with default encryption disabled
Recified.

2022-10-25 12:07 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +  ```
I have updated the image with a new screenshot that does not show the query. Since we would want the user to be able to copy-paste the query used.

2022-10-25 12:12 UTC, RahulSrivastav14 commented on docs/cloud/integrations/tableplus.md
> +```
Rectified. The section is moved to after connect.

2022-10-25 16:17 UTC, judell approved these changes

2022-10-25 16:33 UTC, merged