Add > Steampipe Cloud > Integrations Doc > DBeaver
turbot/steampipe-docs pull request #60
Opened 2022-10-27 17:01 UTC by RahulSrivastav14

2022-10-28 15:31 UTC, judell requested changes
Looks good! Just a few tweaks, thank you.

2022-10-28 15:31 UTC, judell commented on docs/cloud/integrations/dbeaver.md
> +[DBeaver](https://dbeaver.io/download/) Community is open source and free to use on the desktop, while the PRO version can be purchased. In this example we will create a Steampipe Cloud connection wi
```suggestion
[DBeaver](https://dbeaver.io/download/) Community is open source and free to use on the desktop, while the pro version can be purchased. In this example we will create a Steampipe Cloud connection with DBeaver and query the AWS S3 buckets.
```

2022-10-28 15:31 UTC, judell commented on docs/cloud/integrations/dbeaver.md
> +DBeaver comes equipped with a SQL query editor that you may use to write a custom query. For example, we can use this query in the editor to fetch the list of AWS EC2 instance types available in us-e
```suggestion
DBeaver provides a SQL query editor that you may use to write a custom query. For example, we can use this query in the editor to fetch the list of AWS EC2 instance types available in us-east-1 region.
```

2022-10-31 11:58 UTC, RahulSrivastav14 commented on docs/cloud/integrations/dbeaver.md
> +[DBeaver](https://dbeaver.io/download/) Community is open source and free to use on the desktop, while the PRO version can be purchased. In this example we will create a Steampipe Cloud connection wi
Rectified

2022-10-31 11:59 UTC, RahulSrivastav14 commented on docs/cloud/integrations/dbeaver.md
> +DBeaver comes equipped with a SQL query editor that you may use to write a custom query. For example, we can use this query in the editor to fetch the list of AWS EC2 instance types available in us-e
Rectified

2022-11-01 15:31 UTC, merged